apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quay-solver
  namespace: quay-solver
  labels:
    app.kubernetes.io/name: quay-solver
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: authelia-authelia@kubernetescrd,quay-solver-quay-solver-stripprefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: northr3nd.duckdns.org
      http:
        paths:
          - path: /quay-assignment-plan-or-tools
            pathType: Prefix
            backend:
              service:
                name: quay-solver
                port:
                  name: http
  tls:
    - hosts:
        - northr3nd.duckdns.org
      secretName: northr3nd-tls-cert
